"""Initial

Revision ID: facdd4068dfe
Revises: 
Create Date: 2023-01-29 22:46:13.970609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'facdd4068dfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subjects_id', table_name='subjects')
    op.drop_index('ix_subjects_title', table_name='subjects')
    op.drop_table('subjects')
    op.drop_index('ix_lessons_id', table_name='lessons')
    op.drop_index('ix_lessons_title', table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('user_subjects')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_full_name', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_table('results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('homework', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('homework_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('progress', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='results_lesson_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='results_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'lesson_id', name='results_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_teacher', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_full_name', 'users', ['full_name'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('user_subjects',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='user_subjects_subject_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_subjects_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'subject_id', name='user_subjects_pkey')
    )
    op.create_table('lessons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('record', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('homework', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='lessons_subject_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lessons_pkey')
    )
    op.create_index('ix_lessons_title', 'lessons', ['title'], unique=False)
    op.create_index('ix_lessons_id', 'lessons', ['id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subjects_pkey')
    )
    op.create_index('ix_subjects_title', 'subjects', ['title'], unique=False)
    op.create_index('ix_subjects_id', 'subjects', ['id'], unique=False)
    # ### end Alembic commands ###
